apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app  
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app  # Matches the container name in your Dockerfile
        image: zaffarwani/ttrstdfornt:v3
        ports:
        - containerPort: 3000  
          name: http  
        command: ["npm", "run", "dev"]  
