apiVersion: v1
kind: Service
metadata:
  name: my-app-service  
spec:
  type: NodePort
  selector:
    app: my-app 
  ports:
  - port: 80  
    protocol: TCP  
    targetPort: 80  
    NodePort: 31000
  
