import './page.module.css'
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
    
    <html lang="en" >
      <head>
      <body> 
        {children}
      </body>
      </head>
    </html>
   
    
  
  )
}
