name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3  

      - name: Login to Docker Hub 
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Docker image
        run: docker build -t zaffarwani/ttrstdfornt:latest .  

      - name: Push Docker image 
        uses: docker/push-action@v3  
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          tag: zaffarwani/ttrstdfornt:latest  

      - name: Run tests 
        run: | 
          npm install  
          

